os: linux
language: java
dist: focal
jdk:
  - openjdk11

install: true

script: 
  - mvn deploy -Dhttps.protocols=TLSv1.2 --settings travis-settings.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
