language: java
jdk:
  - oraclejdk9
  
branches:
  only:
  - master
  - documentation

script: 
  - mvn --settings travis-settings.xml deploy

after_success:
  - bash <(curl -s https://codecov.io/bash)