coverage:
  range: 75...95

status:
  project:
    default:
      enabled: yes
      target: 85%
      threshold: 2%
    
  patch:
    default:
      enabled: yes
      target: 85%
      threshold: 1%
      
  