name: Chimera CI/CD

on:
  push:
    branches-ignore:
      - master
      - staging
      - stable
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - mvn install
