name: Chimera CI/CD

on:
  push:
    branches:
      - master

env:
  SONATYPE_USERNAME: ${{secrets.SONATYPE_USERNAME}}
  SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - mvn deploy -Dhttps.protocols=TLSv1.2 --settings travis-settings.xml
      - bash <(curl -s https://codecov.io/bash)