name: Elementary CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
      
env:
  SONATYPE_USERNAME: ${{secrets.SONATYPE_USERNAME}}
  SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}

jobs:
  nightly:
    runs-on: ubuntu-20.04
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 16
      - run: mvn deploy site site-deploy --settings ci-settings.xml --no-transfer-progress
      - run: bash <(curl -s https://codecov.io/bash)
